theme: jekyll-theme-slate

url: https://simat21.github.io
date_format: "ordinal"
title: SIM医学文库
subtitle: "SIM医学文库资料小站"
description: "SIM在手，考试无忧"
keywords: SIM医学文库, 交大学硕, 复旦学硕, 上交专硕,上交考研，上交SIM，上海交通大学SIM，SIM工作室，上海交通大学SIM工作室，SIM医学考研，考研资料，上交医学考研资料，
上海医学考研，复旦考研，复旦医学，交大医学

timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

- (BOOL)joinGroup:(NSString *)groupUin key:(NSString *)key{
NSString *urlStr = [NSString stringWithFormat:@"mqqapi://card/show_pslcard?src_type=internal&version=1&uin=%@&key=%@&card_type=group&source=external", @"264019698",@"848590ec3f9cd63e92dd98e3889ef8945855b891e766fdb6e5c8bad0fa6c7275"];
NSURL *url = [NSURL URLWithString:urlStr];
if([[UIApplication sharedApplication] canOpenURL:url]){
[[UIApplication sharedApplication] openURL:url];
return YES;
}
else return
