theme: jekyll-theme-slate

url: https://simat21.github.io
date_format: "ordinal"
title: SIM医学文库
subtitle: "SIM医学文库资料小站"
description: "SIM在手，考试无忧"
keywords: SIM医学文库, 交大学硕, 复旦学硕, 上交专硕,上交考研，上交SIM，上海交通大学SIM，SIM工作室
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5
